#ifndef ERRORS_H
#define ERRORS_H

#define RCS_GENERAL_EXCEPTION (1000)
#define RCS_FT_EXCEPTION (1001) // device is always closed when this exception happens
#define RCS_FILE_CANNOT_ACCESS (1010)
#define RCS_FILE_DEVICE_OPENED (1011)
#define RCS_MODULE_INVALID_ADDR (1100)
#define RCS_MODULE_FAILED (1102)
#define RCS_PORT_INVALID_NUMBER (1103)
#define RCS_MODULE_UNKNOWN_TYPE (1104)
#define RCS_INVALID_SPEED (1105)
#define RCS_INVALID_SCOM_CODE (1106)
#define RCS_INVALID_MODULES_COUNT (1107)
#define RCS_INPUT_NOT_YET_SCANNED (1108)

#define RCS_ALREADY_OPENNED (2001)
#define RCS_CANNOT_OPEN_PORT (2002)
#define RCS_FIRMWARE_TOO_LOW (2003)
#define RCS_DEVICE_DISCONNECTED (2004)
#define RCS_SCANNING_NOT_FINISHED (2010)
#define RCS_NOT_OPENED (2011)
#define RCS_ALREADY_STARTED (2012)
#define RCS_OPENING_NOT_FINISHED (2021)
#define RCS_NO_MODULES (2025)
#define RCS_NOT_STARTED (2031)

#define RCS_INVALID_PACKET (3100)
#define RCS_MODULE_NOT_ANSWERED_CMD (3101)
#define RCS_MODULE_NOT_ANSWERED_CMD_GIVING_UP (3102)
#define RCS_MODULE_OUT_SUM_ERROR (3106)
#define RCS_MODULE_OUT_SUM_ERROR_GIVING_UP (3107)
#define RCS_MODULE_IN_SUM_ERROR (3108)
#define RCS_MODULE_IN_SUM_ERROR_GIVING_UP (3109)

#define RCS_MODULE_NOT_RESPONDED_FB (3121)
#define RCS_MODULE_NOT_RESPONDED_FB_GIVING_UP (3122)
#define RCS_MODULE_IN_FB_SUM_ERROR (3126)
#define RCS_MODULE_IN_FB_SUM_ERROR_GIVING_UP (3127)
#define RCS_MODULE_OUT_FB_SUM_ERROR (3128)
#define RCS_MODULE_OUT_FB_SUM_ERROR_GIVING_UP (3129)
#define RCS_MODULE_INVALID_FB_SUM (3125)
#define RCS_MODULE_NOT_RESPONDING_PWR_ON (3131)

#define RCS_MODULE_PWR_ON_IN_SUM_ERROR (3136)
#define RCS_MODULE_PWR_ON_IN_SUM_ERROR_GIVING_UP (3137)
#define RCS_MODULE_PWR_ON_OUT_SUM_ERROR (3138)
#define RCS_MODULE_PWR_ON_OUT_SUM_ERROR_GIVING_UP (3139)

#define RCS_MODULE_FAIL (3141)
#define RCS_MODULE_RESTORED (3142)
#define RCS_MODULE_INVALID_DATA (3145)

#define RCS_MODULE_REWIND_IN_SUM_ERROR (3162)
#define RCS_MODULE_REWIND_OUT_SUM_ERROR (3163)

#define RCS_MODULE_SCAN_IN_SUM_ERROR (3166)
#define RCS_MODULE_SCAN_IN_SUM_ERROR_GIVING_UP (3167)
#define RCS_MODULE_SCAN_OUT_SUM_ERROR (3168)
#define RCS_MODULE_SCAN_OUT_SUM_ERROR_GIVING_UP (3169)

#define RCS_MODULE_SC_IN_SUM_ERROR (3176)
#define RCS_MODULE_SC_IN_SUM_ERROR_GIVING_UP (3177)
#define RCS_MODULE_SC_OUT_SUM_ERROR (3178)
#define RCS_MODULE_SC_OUT_SUM_ERROR_GIVING_UP (3179)

#define RCS_UNSUPPORTED_API_VERSION (4000)

#endif
